name: User CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci-cd-common:
    uses: chanu-devops/reusable-CICD-yaml/.github/workflows/cicd.yaml@main
    with:
      app-type: nodejs
      micro-services: user